{
 "title": "AirSensEUR - Netherlands Deploy",
 "description": "AirSensEUR Units in The Netherlands",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Gasses - NO2 - NO2B43F - Evaluated",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ASE_NL_03",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_03",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "NO2B43F" }
     ]
    },
    {
     "alias": "ASE_NL_01",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_01",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "NO2B43F" }
     ]
    },
    {
     "alias": "ASE_NL_02",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_02",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "NO2B43F" }
     ]
    },
    {
     "alias": "ASE_NL_04",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_04",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "NO2B43F" }
     ]
    },
    {
     "alias": "ASE_NL_05",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_05",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "NO2B43F" }
     ]
    }
   ]
  },
  {
   "title": "Gasses - O3 - O3_M5 - Evaluated",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ASE_NL_02",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_02",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "O3_M5" }
     ]
    },
    {
     "alias": "ASE_NL_01",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_01",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "O3_M5" }
     ]
    },
    {
     "alias": "ASE_NL_03",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_03",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "O3_M5" }
     ]
    },
    {
     "alias": "ASE_NL_04",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_04",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "O3_M5" }
     ]
    },
    {
     "alias": "ASE_NL_05",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_05",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "O3_M5" }
     ]
    }
   ]
  },
  {
   "title": "Gasses - NO - NOB4_P1 - Evaluated",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ASE_NL_02",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_02",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "NOB4_P1" }
     ]
    },
    {
     "alias": "ASE_NL_01",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_01",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "NOB4_P1" }
     ]
    },
    {
     "alias": "ASE_NL_03",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_03",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "NOB4_P1" }
     ]
    },
    {
     "alias": "ASE_NL_04",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_04",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "NOB4_P1" }
     ]
    },
    {
     "alias": "ASE_NL_05",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_05",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "NOB4_P1" }
     ]
    }
   ]
  },
  {
   "title": "Gasses - CO - COMF200 - Evaluated",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ASE_NL_01",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_01",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "COMF200" }
     ]
    },
    {
     "alias": "ASE_NL_02",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_02",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "COMF200" }
     ]
    },
    {
     "alias": "ASE_NL_03",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_03",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "COMF200" }
     ]
    },
    {
     "alias": "ASE_NL_04",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_04",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "COMF200" }
     ]
    },
    {
     "alias": "ASE_NL_05",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ASE_NL_05",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "COMF200" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "ASE_NL_01",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ASE_NL_01",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Tempe" }
     ]
    },
    {
     "alias": "ASE_NL_02",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ASE_NL_02",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Tempe" }
     ]
    },
    {
     "alias": "ASE_NL_03",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ASE_NL_03",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Tempe" }
     ]
    },
    {
     "alias": "ASE_NL_04",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ASE_NL_04",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Tempe" }
     ]
    },
    {
     "alias": "ASE_NL_05",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ASE_NL_05",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Tempe" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "ASE_NL_01",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ASE_NL_01",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Humid" }
     ]
    },
    {
     "alias": "ASE_NL_02",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ASE_NL_02",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Humid" }
     ]
    },
    {
     "alias": "ASE_NL_03",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ASE_NL_03",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Humid" }
     ]
    },
    {
     "alias": "ASE_NL_04",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ASE_NL_04",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Humid" }
     ]
    },
    {
     "alias": "ASE_NL_05",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ASE_NL_05",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Humid" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "alias": "ASE_NL_01",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ASE_NL_01",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Press" }
     ]
    },
    {
     "alias": "ASE_NL_02",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ASE_NL_02",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Press" }
     ]
    },
    {
     "alias": "ASE_NL_03",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ASE_NL_03",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Press" }
     ]
    },
    {
     "alias": "ASE_NL_04",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ASE_NL_04",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Press" }
     ]
    },
    {
     "alias": "ASE_NL_05",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ASE_NL_05",
     "select": [
      [
       { "params": [ "sampleEvaluatedVal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Press" }
     ]
    }
   ]
  },
  {
   "title": "Longitude - ASE_NL_02",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 47 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "ASE_NL_02",
     "select": [
      [
       { "params": [ "longitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "channel", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Latitude - ASE_NL_02",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 47 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "ASE_NL_02",
     "measurement": "ASE_NL_02",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "channel", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Altitude ASE_NL_02",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 47 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Altitude ASE_NL_02",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ASE_NL_02",
     "select": [
      [
       { "params": [ "altitude" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "channel", "operator": "=", "value": "0" }
     ]
    }
   ]
  }
 ]
}